In [0]:
import pandas as pd
import numpy as np

In [0]:
df = pd.read_csv('COVID-19.csv')

In [0]:
bins= [0,10,20,30,40,50,60,70,80,100]
labels = ['a','b','c','d','e','f','g','h','i']
Age = pd.cut(df['age'], bins=bins, labels=labels, right=False)

In [0]:
df["Age"]=Age
df=df.drop(['age'],axis=1)

In [0]:
df=pd.concat([df,pd.get_dummies(df['Age'],drop_first=True)],axis=1)

In [6]:
df = df.drop (['Age'],axis=1)
df.head()

   Sno  gender  body temperature  Dry Cough  sour throat  ...  e  f  g  h  i
0    1       1              98.6          0            0  ...  0  0  0  0  0
1    2       1              99.0          1            0  ...  0  0  0  0  0
2    3       0             102.0          1            1  ...  0  1  0  0  0
3    4       0             100.0          0            0  ...  1  0  0  0  0
4    5       1              99.2          0            1  ...  0  0  0  0  0

[5 rows x 28 columns]

In [0]:
bins= [96,98.6,102,110]
labels = ['normal','fever','high fever']
Temp = pd.cut(df['body temperature'], bins=bins, labels=labels, right=False)

In [0]:
df["Temp"]=Temp
df=df.drop(['body temperature'],axis=1)

In [9]:
df=pd.concat([df,pd.get_dummies(df['Temp'],drop_first=True)],axis=1)
df = df.drop (['Temp'],axis=1)
df.head()

   Sno  gender  Dry Cough  sour throat  weakness  ...  g  h  i  fever  high fever
0    1       1          0            0         0  ...  0  0  0      1           0
1    2       1          1            0         0  ...  0  0  0      1           0
2    3       0          1            1         1  ...  0  0  0      0           1
3    4       0          0            0         0  ...  0  0  0      1           0
4    5       1          0            1         0  ...  0  0  0      1           0

[5 rows x 29 columns]

In [0]:
x=df.drop(['Corona result' , 'Sno' ] , axis=1)

In [11]:
x.head()

   gender  Dry Cough  sour throat  weakness  ...  h  i  fever  high fever
0       1          0            0         0  ...  0  0      1           0
1       1          1            0         0  ...  0  0      1           0
2       0          1            1         1  ...  0  0      0           1
3       0          0            0         0  ...  0  0      1           0
4       1          0            1         0  ...  0  0      1           0

[5 rows x 27 columns]

In [0]:
y=df['Corona result']

In [13]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , random_state = 2 , test_size = 0.20)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
y_cat = pd.get_dummies(y_train)

(101, 27)
(101,)
(26, 27)
(26,)

In [14]:
from keras.models import Sequential
model = Sequential()
from keras.layers import Dense
model.add(Dense(units=127 , input_shape=(27,),activation='relu',kernel_initializer='glorot_uniform'))
model.add(Dense(units=50 ,activation='relu',kernel_initializer='glorot_uniform'))
model.add(Dense(units=20 , activation='relu',kernel_initializer='glorot_uniform'))
model.add(Dense(units=60 , activation='relu',kernel_initializer='glorot_uniform'))
model.add(Dense(units=3 , activation='softmax'))
model.summary()
from keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.001),  
              loss='categorical_crossentropy',
             metrics=['accuracy'] )
model.fit(x_train,y_cat, epochs=44)

Using TensorFlow backend.

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 127)               3556
_________________________________________________________________
dense_2 (Dense)              (None, 50)                6400
_________________________________________________________________
dense_3 (Dense)              (None, 20)                1020
_________________________________________________________________
dense_4 (Dense)              (None, 60)                1260
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 183
=================================================================
Total params: 12,419
Trainable params: 12,419
Non-trainable params: 0
_________________________________________________________________
Epoch 1/44
101/101 [==============================] - 0s 1ms/step - loss: 1.1140 - accuracy: 0.2970
Epoch 2/44
101/101 [==============================] - 0s 124us/step - loss: 1.0752 - accuracy: 0.5644
Epoch 3/44
101/101 [==============================] - 0s 111us/step - loss: 1.0492 - accuracy: 0.5941
Epoch 4/44
101/101 [==============================] - 0s 84us/step - loss: 1.0272 - accuracy: 0.5743
Epoch 5/44
101/101 [==============================] - 0s 112us/step - loss: 1.0000 - accuracy: 0.5743
Epoch 6/44
101/101 [==============================] - 0s 103us/step - loss: 0.9661 - accuracy: 0.5743
Epoch 7/44
101/101 [==============================] - 0s 135us/step - loss: 0.9314 - accuracy: 0.5743
Epoch 8/44
101/101 [==============================] - 0s 107us/step - loss: 0.8985 - accuracy: 0.5842
Epoch 9/44
101/101 [==============================] - 0s 104us/step - loss: 0.8719 - accuracy: 0.5941
Epoch 10/44
101/101 [==============================] - 0s 107us/step - loss: 0.8345 - accuracy: 0.6238
Epoch 11/44
101/101 [==============================] - 0s 84us/step - loss: 0.7931 - accuracy: 0.6436
Epoch 12/44
101/101 [==============================] - 0s 91us/step - loss: 0.7497 - accuracy: 0.7327
Epoch 13/44
101/101 [==============================] - 0s 92us/step - loss: 0.7114 - accuracy: 0.7723
Epoch 14/44
101/101 [==============================] - 0s 97us/step - loss: 0.6501 - accuracy: 0.7822
Epoch 15/44
101/101 [==============================] - 0s 113us/step - loss: 0.5865 - accuracy: 0.7921
Epoch 16/44
101/101 [==============================] - 0s 110us/step - loss: 0.5262 - accuracy: 0.8020
Epoch 17/44
101/101 [==============================] - 0s 97us/step - loss: 0.4747 - accuracy: 0.8614
Epoch 18/44
101/101 [==============================] - 0s 85us/step - loss: 0.4461 - accuracy: 0.8614
Epoch 19/44
101/101 [==============================] - 0s 101us/step - loss: 0.3940 - accuracy: 0.8812
Epoch 20/44
101/101 [==============================] - 0s 83us/step - loss: 0.3447 - accuracy: 0.8911
Epoch 21/44
101/101 [==============================] - 0s 73us/step - loss: 0.3110 - accuracy: 0.9109
Epoch 22/44
101/101 [==============================] - 0s 110us/step - loss: 0.2772 - accuracy: 0.9505
Epoch 23/44
101/101 [==============================] - 0s 95us/step - loss: 0.2389 - accuracy: 0.9505
Epoch 24/44
101/101 [==============================] - 0s 101us/step - loss: 0.2321 - accuracy: 0.9505
Epoch 25/44
101/101 [==============================] - 0s 104us/step - loss: 0.2268 - accuracy: 0.9406
Epoch 26/44
101/101 [==============================] - 0s 119us/step - loss: 0.2038 - accuracy: 0.9307
Epoch 27/44
101/101 [==============================] - 0s 101us/step - loss: 0.1703 - accuracy: 0.9505
Epoch 28/44
101/101 [==============================] - 0s 100us/step - loss: 0.1746 - accuracy: 0.9505
Epoch 29/44
101/101 [==============================] - 0s 79us/step - loss: 0.1597 - accuracy: 0.9604
Epoch 30/44
101/101 [==============================] - 0s 90us/step - loss: 0.1474 - accuracy: 0.9703
Epoch 31/44
101/101 [==============================] - 0s 82us/step - loss: 0.1278 - accuracy: 0.9703
Epoch 32/44
101/101 [==============================] - 0s 76us/step - loss: 0.1224 - accuracy: 0.9703
Epoch 33/44
101/101 [==============================] - 0s 116us/step - loss: 0.1178 - accuracy: 0.9703
Epoch 34/44
101/101 [==============================] - 0s 103us/step - loss: 0.1102 - accuracy: 0.9703
Epoch 35/44
101/101 [==============================] - 0s 115us/step - loss: 0.1026 - accuracy: 0.9802
Epoch 36/44
101/101 [==============================] - 0s 114us/step - loss: 0.0970 - accuracy: 0.9703
Epoch 37/44
101/101 [==============================] - 0s 114us/step - loss: 0.0887 - accuracy: 0.9703
Epoch 38/44
101/101 [==============================] - 0s 133us/step - loss: 0.0890 - accuracy: 0.9703
Epoch 39/44
101/101 [==============================] - 0s 109us/step - loss: 0.0797 - accuracy: 0.9802
Epoch 40/44
101/101 [==============================] - 0s 99us/step - loss: 0.0643 - accuracy: 0.9703
Epoch 41/44
101/101 [==============================] - 0s 86us/step - loss: 0.0787 - accuracy: 0.9703
Epoch 42/44
101/101 [==============================] - 0s 108us/step - loss: 0.0709 - accuracy: 0.9703
Epoch 43/44
101/101 [==============================] - 0s 128us/step - loss: 0.0546 - accuracy: 1.0000
Epoch 44/44
101/101 [==============================] - 0s 82us/step - loss: 0.0537 - accuracy: 0.9901

In [0]:
model.save('finalmodel99-01.h5')