In [0]:
import pandas as pd
import numpy as np

In [0]:
test = pd.read_csv("test_data.csv")

In [3]:
test.head()

   age  gender  ...  change in appetide  Loss of sense of smell
0   20       1  ...                   0                       0
1   20       1  ...                   0                       0
2   22       1  ...                   0                       0
3   21       0  ...                   0                       0
4   22       1  ...                   0                       0

[5 rows x 19 columns]

In [0]:
bins= [0,10,20,30,40,50,60,70,80,90,100]
labels = ['a','b','c','d','e','f','g','h','i','j']
Age = pd.cut(test['age'], bins=bins, labels=labels, right=False)

In [0]:
test["Age"]=Age
test=test.drop(['age'],axis=1)

In [0]:
test=pd.concat([test,pd.get_dummies(test['Age'],drop_first=True)],axis=1)

In [7]:
test = test.drop (['Age'],axis=1)
test.head()

   gender  body temprature  Dry Cough  sour throat  weakness  ...  f  g  h  i  j
0       1             97.0          0            0         0  ...  0  0  0  0  0
1       1             97.0          0            0         0  ...  0  0  0  0  0
2       1             97.0          0            0         0  ...  0  0  0  0  0
3       0            101.0          0            0         0  ...  0  0  0  0  0
4       1             97.0          1            0         0  ...  0  0  0  0  0

[5 rows x 27 columns]

In [8]:
bins= [96,98.6,102,110]
labels = ['normal','fever','high fever']
Temp = pd.cut(test['body temprature'], bins=bins, labels=labels, right=False)
test["Temp"]=Temp
test=test.drop(['body temprature'],axis=1)
test=pd.concat([test,pd.get_dummies(test['Temp'],drop_first=True)],axis=1)
test = test.drop (['Temp'],axis=1)
test.head()

   gender  Dry Cough  sour throat  weakness  ...  i  j  fever  high fever
0       1          0            0         0  ...  0  0      0           0
1       1          0            0         0  ...  0  0      0           0
2       1          0            0         0  ...  0  0      0           0
3       0          0            0         0  ...  0  0      1           0
4       1          1            0         0  ...  0  0      0           0

[5 rows x 28 columns]

In [9]:
from keras.models import load_model as l
model= l('updatemodel99-01.h5')
m = model.predict(test)

Using TensorFlow backend.

In [10]:
'''y_pred = []
for i in range (len(test)):
  m=model.predict(test)
  m=list(m[0])
  y_pred.append(m.index(max(m)))'''

'y_pred = []\nfor i in range (len(test)):\n  m=model.predict(test)\n  m=list(m[0])\n  y_pred.append(m.index(max(m)))'

In [0]:
y_pred = []
for i in m:
  y_pred.append(np.where(i==i.max()))

In [0]:
test['predicted result'] = y_pred

In [13]:
test.head()

   gender  Dry Cough  sour throat  ...  fever  high fever  predicted result
0       1          0            0  ...      0           0            ([1],)
1       1          0            0  ...      0           0            ([0],)
2       1          0            0  ...      0           0            ([0],)
3       0          0            0  ...      1           0            ([0],)
4       1          1            0  ...      0           0            ([0],)

[5 rows x 29 columns]

In [0]:
test.to_csv(r'/content/predicted_result_dataset.csv')